tr.po
torikulhabib/niki pull request #19
Opened 2020-03-05 21:54 UTC by safak45x

I hope it's true now

2020-03-06 05:21 UTC, NathanBnm requested changes
This one is fine, you just have to remove the line with "fuzzy" at the beginning of the file and it will be good.

2020-03-06 15:31 UTC, safak45x commented
> Bu iyi, sadece dosyanın başında "bulanık" ile satır kaldırmak zorunda ve iyi olacak.

okey fix bug

2020-03-06 15:36 UTC, NathanBnm approved these changes

2020-03-13 12:26 UTC, merged

2020-03-13 12:26 UTC, torikulhabib commented
thanks